In [64]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split

In [65]:
df = pd.read_csv("songs_normalize.csv")
df

artist                                    song  duration_ms  \
0     Britney Spears                  Oops!...I Did It Again       211160   
1          blink-182                    All The Small Things       167066   
2         Faith Hill                                 Breathe       250546   
3           Bon Jovi                            It's My Life       224493   
4             *NSYNC                             Bye Bye Bye       200560   
...              ...                                     ...          ...   
1995  Jonas Brothers                                  Sucker       181026   
1996    Taylor Swift                            Cruel Summer       178426   
1997    Blanco Brown                              The Git Up       200593   
1998       Sam Smith  Dancing With A Stranger (with Normani)       171029   
1999     Post Malone                                 Circles       215280   

     explicit  year  popularity  danceability  energy  key  loudness  mode  \
0       False  2000        77.0         0.751   0.834    1    -5.444     0   
1       False  1999        79.0         0.434   0.897    0    -4.918     1   
2       False  1999        66.0         0.529   0.496    7    -9.007     1   
3       False  2000        78.0         0.551   0.913    0    -4.063     0   
4       False  2000        65.0         0.614   0.928    8    -4.806     0   
...       ...   ...         ...           ...     ...  ...       ...   ...   
1995    False  2019        79.0         0.842   0.734    1    -5.065     0   
1996    False  2019        78.0         0.552   0.702    9    -5.707     1   
1997    False  2019        69.0         0.847   0.678    9    -8.635     1   
1998    False  2019        75.0         0.741   0.520    8    -7.513     1   
1999    False  2019        85.0         0.695   0.762    0    -3.497     1   

      speechiness  acousticness  instrumentalness  liveness  valence    tempo  \
0          0.0437        0.3000          0.000018    0.3550    0.894   95.053   
1          0.0488        0.0103          0.000000    0.6120    0.684  148.726   
2          0.0290        0.1730          0.000000    0.2510    0.278  136.859   
3          0.0466        0.0263          0.000013    0.3470    0.544  119.992   
4          0.0516        0.0408          0.001040    0.0845    0.879  172.656   
...           ...           ...               ...       ...      ...      ...   
1995       0.0588        0.0427          0.000000    0.1060    0.952  137.958   
1996       0.1570        0.1170          0.000021    0.1050    0.564  169.994   
1997       0.1090        0.0669          0.000000    0.2740    0.811   97.984   
1998       0.0656        0.4500          0.000002    0.2220    0.347  102.998   
1999       0.0395        0.1920          0.002440    0.0863    0.553  120.042   

                 genre  
0                  pop  
1            rock, pop  
2         pop, country  
3          rock, metal  
4                  pop  
...                ...  
1995               pop  
1996               pop  
1997  hip hop, country  
1998               pop  
1999           hip hop  

[2000 rows x 18 columns]

In [66]:
df.isna().sum()

artist               0
song                 0
duration_ms          0
explicit             9
year                 0
popularity           8
danceability        26
energy               8
key                  0
loudness             0
mode                 0
speechiness          0
acousticness         0
instrumentalness     0
liveness             0
valence              0
tempo                0
genre                0
dtype: int64

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   artist            2000 non-null   object 
 1   song              2000 non-null   object 
 2   duration_ms       2000 non-null   int64  
 3   explicit          1991 non-null   object 
 4   year              2000 non-null   int64  
 5   popularity        1992 non-null   float64
 6   danceability      1974 non-null   float64
 7   energy            1992 non-null   float64
 8   key               2000 non-null   int64  
 9   loudness          2000 non-null   float64
 10  mode              2000 non-null   int64  
 11  speechiness       2000 non-null   float64
 12  acousticness      2000 non-null   float64
 13  instrumentalness  2000 non-null   float64
 14  liveness          2000 non-null   float64
 15  valence           2000 non-null   float64
 16  tempo             2000 non-null   float64


## Membagi Training set 70 : Testing set 30

In [68]:
X = df.iloc[:,:-1] 
Y = df.iloc[:,-1] 

In [69]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3)

In [70]:
print("Dimensi X_train : ", X_train.shape)
print("Dimensi X_train : ", X_test.shape)
print("Dimensi y_train : ", y_train.shape)
print("Dimensi y_test : ", X_test.shape)

Dimensi X_train :  (1400, 17)
Dimensi X_train :  (600, 17)
Dimensi y_train :  (1400,)
Dimensi y_test :  (600, 17)


## Melakukan Normalisasi Data 

In [71]:
from sklearn.preprocessing import MinMaxScaler

In [72]:
mm = MinMaxScaler()
x_scaled = mm.fit_transform(
df[['danceability','popularity','energy']])

In [73]:
normalisasi = pd.DataFrame(x_scaled)
normalisasi.head(5)

0         1         2
0  0.735225  0.865169  0.825230
1  0.360520  0.887640  0.891961
2  0.472813  0.741573  0.467217
3  0.498818  0.876404  0.908908
4  0.573286  0.730337  0.924796

## Melakukan Standarisasi Pada Dataset 

In [74]:
from sklearn.preprocessing import StandardScaler 

In [75]:
ss = StandardScaler()
data = np.asarray(df[['danceability','popularity','energy']])
Scaled_data = ss.fit_transform(data) 

In [76]:
print("Nilai Data Sebelum scaling : ") 
print(data) 
print("Nilai standar deviasi: ", np.std(data))
print("============================================")
print("\n Nilai Data setelah scaling : ") 
print(Scaled_data) 
print("Nilai standar deviasi: ", np.std(Scaled_data)) 

Nilai Data Sebelum scaling : 
[[ 0.751 77.     0.834]
 [ 0.434 79.     0.897]
 [ 0.529 66.     0.496]
 ...
 [ 0.847 69.     0.678]
 [ 0.741 75.     0.52 ]
 [ 0.695 85.     0.762]]
Nilai standar deviasi:  nan

 Nilai Data setelah scaling : 
[[ 0.59820498  0.80330109  0.74562752]
 [-1.65929305  0.89695804  1.15806988]
 [-0.98275579  0.28818788 -1.46715844]
 ...
 [ 1.28186369  0.4286733  -0.27565831]
 [ 0.52699053  0.70964415 -1.31003754]
 [ 0.19940406  1.17792888  0.27426483]]
Nilai standar deviasi:  nan


## Melakukan Data Cleaning

In [77]:
from sklearn.impute import SimpleImputer

In [78]:
df.isna().sum()

artist               0
song                 0
duration_ms          0
explicit             9
year                 0
popularity           8
danceability        26
energy               8
key                  0
loudness             0
mode                 0
speechiness          0
acousticness         0
instrumentalness     0
liveness             0
valence              0
tempo                0
genre                0
dtype: int64

## Merubah Nilai Null Yang Punya Tipe Data Desimal

In [79]:
imputer = SimpleImputer(strategy = 'mean')
df["energy"] = imputer.fit_transform(df[["popularity"]])
print("\nJumlah null : ")
print(df.isna().sum())


Jumlah null : 
artist               0
song                 0
duration_ms          0
explicit             9
year                 0
popularity           8
danceability        26
energy               0
key                  0
loudness             0
mode                 0
speechiness          0
acousticness         0
instrumentalness     0
liveness             0
valence              0
tempo                0
genre                0
dtype: int64


## Merubah Nilai Null Yang Punya Tipe Data Bilangan Bulat

In [80]:
imputer = SimpleImputer(strategy = 'most_frequent')
df["popularity"] = imputer.fit_transform(df[["popularity"]])
print("\nJumlah null : ")
print(df.isna().sum())


Jumlah null : 
artist               0
song                 0
duration_ms          0
explicit             9
year                 0
popularity           0
danceability        26
energy               0
key                  0
loudness             0
mode                 0
speechiness          0
acousticness         0
instrumentalness     0
liveness             0
valence              0
tempo                0
genre                0
dtype: int64


## Merubah Nilai Null Yang Punya Tipe Data Kategorikal

In [81]:
imputer = SimpleImputer(strategy = 'most_frequent')
df["explicit"] = imputer.fit_transform(df[["explicit"]])
print("\nJumlah null : ")
print(df.isna().sum())


Jumlah null : 
artist               0
song                 0
duration_ms          0
explicit             0
year                 0
popularity           0
danceability        26
energy               0
key                  0
loudness             0
mode                 0
speechiness          0
acousticness         0
instrumentalness     0
liveness             0
valence              0
tempo                0
genre                0
dtype: int64


## Melakukan Data Cleaning Pada Data Dengan Nilai Duplikat

In [82]:
df[df.duplicated()]

artist                                  song  duration_ms  \
98            Sting                           Desert Rose       285960   
99        Melanie C               Never Be The Same Again       294200   
100         Aaliyah                             Try Again       284000   
101       Anastacia           I'm Outta Love - Radio Edit       245400   
102    Alice Deejay                      Better Off Alone       214883   
...             ...                                   ...          ...   
1731      Rob $tone  Chill Bill (feat. J. Davi$ & Spooks)       177184   
1832      Jax Jones                               Breathe       207629   
1921   Travis Scott                            SICKO MODE       312820   
1929  Billie Eilish                  lovely (with Khalid)       200185   
1984    Post Malone                            Better Now       231266   

     explicit  year  popularity  danceability  energy  key  loudness  mode  \
98      False  1999        62.0           NaN    62.0    0    -7.920     0   
99      False  1999        61.0           NaN    61.0    3    -5.153     1   
100     False  2002        53.0           NaN    53.0    6    -5.642     0   
101     False  1999        64.0           NaN    64.0   10    -5.800     0   
102     False  2000        73.0           NaN    73.0    8    -6.149     0   
...       ...   ...         ...           ...     ...  ...       ...   ...   
1731     True  2016        76.0         0.886    76.0    6   -10.028     1   
1832    False  2017        58.0         0.722    58.0   11    -5.520     0   
1921     True  2018        81.0         0.834    81.0    8    -3.714     1   
1929    False  2018        86.0         0.351    86.0    4   -10.109     0   
1984     True  2018        80.0         0.680    80.0   10    -5.804     1   

      speechiness  acousticness  instrumentalness  liveness  valence    tempo  \
98         0.0304       0.01100          0.000000    0.1060    0.147  111.989   
99         0.0478       0.09210          0.000000    0.1190    0.398  160.067   
100        0.2900       0.08070          0.000000    0.0841    0.731   93.020   
101        0.0560       0.39600          0.000000    0.0771    0.649  119.410   
102        0.0552       0.00181          0.691000    0.2850    0.782  136.953   
...           ...           ...               ...       ...      ...      ...   
1731       0.1450       0.03120          0.000990    0.0906    0.230  108.034   
1832       0.0363       0.02340          0.000157    0.1430    0.686  125.985   
1921       0.2220       0.00513          0.000000    0.1240    0.446  155.008   
1929       0.0333       0.93400          0.000000    0.0950    0.120  115.284   
1984       0.0400       0.33100          0.000000    0.1350    0.341  145.038   

                               genre  
98                         rock, pop  
99             pop, Dance/Electronic  
100                hip hop, pop, R&B  
101                              pop  
102                              pop  
...                              ...  
1731                         hip hop  
1832  hip hop, pop, Dance/Electronic  
1921       hip hop, Dance/Electronic  
1929           pop, Dance/Electronic  
1984                         hip hop  

[64 rows x 18 columns]

In [83]:
df.drop_duplicates(inplace=True)

In [84]:
print("Setelah menggunakan drop_duplicates()") 
print("Jumlah Nilai Duplikat:",df.duplicated().sum())

Setelah menggunakan drop_duplicates()
Jumlah Nilai Duplikat: 0


## Merubah Tipe Data Angka Menjadi Kategorikal

In [85]:
from sklearn.preprocessing import OrdinalEncoder 

In [86]:
encoder = OrdinalEncoder() 
df["jobEnc"] = encoder.fit_transform(df[["genre"]]) 
df.head()

artist                    song  duration_ms explicit  year  \
0  Britney Spears  Oops!...I Did It Again       211160    False  2000   
1       blink-182    All The Small Things       167066    False  1999   
2      Faith Hill                 Breathe       250546    False  1999   
3        Bon Jovi            It's My Life       224493    False  2000   
4          *NSYNC             Bye Bye Bye       200560    False  2000   

   popularity  danceability  energy  key  loudness  mode  speechiness  \
0        77.0         0.751    77.0    1    -5.444     0       0.0437   
1        79.0         0.434    79.0    0    -4.918     1       0.0488   
2        66.0         0.529    66.0    7    -9.007     1       0.0290   
3        78.0         0.551    78.0    0    -4.063     0       0.0466   
4        65.0         0.614    65.0    8    -4.806     0       0.0516   

   acousticness  instrumentalness  liveness  valence    tempo         genre  \
0        0.3000          0.000018    0.3550    0.894   95.053           pop   
1        0.0103          0.000000    0.6120    0.684  148.726     rock, pop   
2        0.1730          0.000000    0.2510    0.278  136.859  pop, country   
3        0.0263          0.000013    0.3470    0.544  119.992   rock, metal   
4        0.0408          0.001040    0.0845    0.879  172.656           pop   

   jobEnc  
0    30.0  
1    54.0  
2    36.0  
3    53.0  
4    30.0

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1936 entries, 0 to 1999
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   artist            1936 non-null   object 
 1   song              1936 non-null   object 
 2   duration_ms       1936 non-null   int64  
 3   explicit          1936 non-null   object 
 4   year              1936 non-null   int64  
 5   popularity        1936 non-null   float64
 6   danceability      1916 non-null   float64
 7   energy            1936 non-null   float64
 8   key               1936 non-null   int64  
 9   loudness          1936 non-null   float64
 10  mode              1936 non-null   int64  
 11  speechiness       1936 non-null   float64
 12  acousticness      1936 non-null   float64
 13  instrumentalness  1936 non-null   float64
 14  liveness          1936 non-null   float64
 15  valence           1936 non-null   float64
 16  tempo             1936 non-null   float64


## Melakukan One Hot Encoding

In [88]:
from sklearn.preprocessing import OneHotEncoder 

In [89]:
encoder = OneHotEncoder(sparse=False) 
explicitEnc = encoder.fit_transform(df[["explicit"]]) 
explicitEnc = pd.DataFrame(explicitEnc) 
df = df.join(explicitEnc) 
df 

artist                                    song  duration_ms  \
0     Britney Spears                  Oops!...I Did It Again       211160   
1          blink-182                    All The Small Things       167066   
2         Faith Hill                                 Breathe       250546   
3           Bon Jovi                            It's My Life       224493   
4             *NSYNC                             Bye Bye Bye       200560   
...              ...                                     ...          ...   
1995  Jonas Brothers                                  Sucker       181026   
1996    Taylor Swift                            Cruel Summer       178426   
1997    Blanco Brown                              The Git Up       200593   
1998       Sam Smith  Dancing With A Stranger (with Normani)       171029   
1999     Post Malone                                 Circles       215280   

     explicit  year  popularity  danceability  energy  key  loudness  ...  \
0       False  2000        77.0         0.751    77.0    1    -5.444  ...   
1       False  1999        79.0         0.434    79.0    0    -4.918  ...   
2       False  1999        66.0         0.529    66.0    7    -9.007  ...   
3       False  2000        78.0         0.551    78.0    0    -4.063  ...   
4       False  2000        65.0         0.614    65.0    8    -4.806  ...   
...       ...   ...         ...           ...     ...  ...       ...  ...   
1995    False  2019        79.0         0.842    79.0    1    -5.065  ...   
1996    False  2019        78.0         0.552    78.0    9    -5.707  ...   
1997    False  2019        69.0         0.847    69.0    9    -8.635  ...   
1998    False  2019        75.0         0.741    75.0    8    -7.513  ...   
1999    False  2019        85.0         0.695    85.0    0    -3.497  ...   

      speechiness  acousticness  instrumentalness  liveness  valence    tempo  \
0          0.0437        0.3000          0.000018    0.3550    0.894   95.053   
1          0.0488        0.0103          0.000000    0.6120    0.684  148.726   
2          0.0290        0.1730          0.000000    0.2510    0.278  136.859   
3          0.0466        0.0263          0.000013    0.3470    0.544  119.992   
4          0.0516        0.0408          0.001040    0.0845    0.879  172.656   
...           ...           ...               ...       ...      ...      ...   
1995       0.0588        0.0427          0.000000    0.1060    0.952  137.958   
1996       0.1570        0.1170          0.000021    0.1050    0.564  169.994   
1997       0.1090        0.0669          0.000000    0.2740    0.811   97.984   
1998       0.0656        0.4500          0.000002    0.2220    0.347  102.998   
1999       0.0395        0.1920          0.002440    0.0863    0.553  120.042   

                 genre jobEnc    0    1  
0                  pop   30.0  1.0  0.0  
1            rock, pop   54.0  1.0  0.0  
2         pop, country   36.0  1.0  0.0  
3          rock, metal   53.0  1.0  0.0  
4                  pop   30.0  1.0  0.0  
...                ...    ...  ...  ...  
1995               pop   30.0  NaN  NaN  
1996               pop   30.0  NaN  NaN  
1997  hip hop, country   17.0  NaN  NaN  
1998               pop   30.0  NaN  NaN  
1999           hip hop   14.0  NaN  NaN  

[1936 rows x 21 columns]

## Terimakasih.