## Nama : Muhammad Fajrianur
## Nim    : 2009106040
## Kelas : Informatika A 2020

# Posttest_7

In [22]:
import tensorflow as tf

## Membuat tensor dengan shape(5,5) dengan nilai random yg di simpan dalam variable random_tensor

In [23]:
random_tensor = tf.random.normal([5,5],mean=0,stddev=1,seed=1) 
print(random_tensor)

tf.Tensor(
[[-0.32386488  0.99133694  0.14024267  1.2573972   0.09992335]
 [ 0.18983224 -0.28711194 -1.7413595   1.8718754  -2.0104504 ]
 [-1.4673029  -1.2721989  -0.7803738   0.94073033 -0.06164822]
 [-2.0842526   0.61423135 -1.451092   -0.88693523 -0.96740866]
 [ 0.94831836 -0.6974499   0.5391437  -0.52970064 -2.0105364 ]], shape=(5, 5), dtype=float32)


## Membuat tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable

In [24]:
list = [[2,3,5,7,11],[13,17,19,23,29],[31,37,41,43,47],[53,59,61,67,71],[73,79,83,89,97]]
prime_tensor = tf.convert_to_tensor(list, dtype=tf.float32)
prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)

## Menampilkan dimensi dari kedua variable tersebut

In [25]:
random_tensor.get_shape()

TensorShape([5, 5])

In [26]:
random_tensor.shape

TensorShape([5, 5])

## Menampilkan hasil dari perhitungan aritmetika 2 variable (penambah, pengurangan, pembagian, perkalian, pangkat, dan logaritma.)

## Penambah

In [27]:
print(tf.add(random_tensor, prime_tensor))

tf.Tensor(
[[ 1.6761351  3.9913368  5.1402426  8.257397  11.099923 ]
 [13.189833  16.712889  17.25864   24.871876  26.98955  ]
 [29.532698  35.727802  40.219627  43.94073   46.93835  ]
 [50.91575   59.61423   59.54891   66.11307   70.03259  ]
 [73.94832   78.30255   83.53915   88.4703    94.98946  ]], shape=(5, 5), dtype=float32)


## Pengurangan

In [28]:
print(tf.subtract(random_tensor, prime_tensor))

tf.Tensor(
[[ -2.323865   -2.0086632  -4.8597574  -5.742603  -10.900077 ]
 [-12.810167  -17.287111  -20.74136   -21.128124  -31.01045  ]
 [-32.467304  -38.272198  -41.780373  -42.05927   -47.06165  ]
 [-55.08425   -58.38577   -62.45109   -67.88693   -71.96741  ]
 [-72.05168   -79.69745   -82.46085   -89.5297    -99.01054  ]], shape=(5, 5), dtype=float32)


## Pembagian

In [29]:
print(tf.divide(random_tensor,prime_tensor))

tf.Tensor(
[[-0.16193244  0.33044565  0.02804853  0.17962816  0.00908394]
 [ 0.01460248 -0.01688894 -0.0916505   0.08138589 -0.06932587]
 [-0.04733235 -0.03438376 -0.01903351  0.02187745 -0.00131166]
 [-0.03932552  0.0104107  -0.02378839 -0.01323784 -0.01362547]
 [ 0.01299066 -0.00882848  0.00649571 -0.00595169 -0.02072718]], shape=(5, 5), dtype=float32)


## Perkalian

In [30]:
print(tf.multiply(random_tensor, prime_tensor))

tf.Tensor(
[[  -0.64772975    2.974011      0.70121336    8.801781      1.0991569 ]
 [   2.4678192    -4.880903    -33.08583      43.053135    -58.303062  ]
 [ -45.48639     -47.07136     -31.995327     40.451405     -2.8974664 ]
 [-110.465385     36.23965     -88.51661     -59.42466     -68.68601   ]
 [  69.22724     -55.098545     44.748924    -47.143356   -195.02203   ]], shape=(5, 5), dtype=float32)


## Pangkat

In [31]:
print(tf.pow(random_tensor, prime_tensor))

tf.Tensor(
[[ 1.0488846e-01  9.7423530e-01  5.4250133e-05  4.9694390e+00
   9.9160073e-12]
 [ 4.1572837e-10 -6.1216887e-10 -3.7746809e+04  1.8296565e+06
  -6.2446387e+08]
 [-1.4524903e+05 -7.3881514e+03 -3.8406979e-05  7.2277203e-02
  -0.0000000e+00]
 [-8.0235882e+16  3.2477805e-13 -7.3011604e+09 -3.2266942e-04
  -9.5127881e-02]
 [ 2.0780388e-02 -4.3403966e-13  5.3885902e-23 -2.7460855e-25
  -2.6379033e+29]], shape=(5, 5), dtype=float32)


## logaritma

In [41]:
print(tf.math.log(random_tensor, prime_tensor))

tf.Tensor(
[[        nan -0.0087008  -1.964381    0.22904386 -2.3033519 ]
 [-1.6616145          nan         nan  0.62694085         nan]
 [        nan         nan         nan -0.06109876         nan]
 [        nan -0.48738366         nan         nan         nan]
 [-0.05306501         nan -0.6177732          nan         nan]], shape=(5, 5), dtype=float32)


## Menampilkan nilai Min Max  dari variable random_tensor

## Max

In [42]:
print(tf.argmax(random_tensor, axis=0))

tf.Tensor([4 0 4 1 0], shape=(5,), dtype=int64)


In [43]:
print(tf.argsort(random_tensor, direction='ASCENDING'))

tf.Tensor(
[[0 4 2 1 3]
 [4 2 1 0 3]
 [0 1 2 4 3]
 [0 2 4 3 1]
 [4 1 3 2 0]], shape=(5, 5), dtype=int32)


## Min

In [44]:
print(tf.argmin(random_tensor, axis=0))

tf.Tensor([3 2 1 3 4], shape=(5,), dtype=int64)


In [45]:
print(tf.argsort(random_tensor, direction='ASCENDING'))

tf.Tensor(
[[0 4 2 1 3]
 [4 2 1 0 3]
 [0 1 2 4 3]
 [0 2 4 3 1]
 [4 1 3 2 0]], shape=(5, 5), dtype=int32)


In [46]:
print(tf.argmin(random_tensor, axis=1))

tf.Tensor([0 4 0 0 4], shape=(5,), dtype=int64)


In [47]:
print(tf.sort(random_tensor, direction='ASCENDING'))

tf.Tensor(
[[-0.32386488  0.09992335  0.14024267  0.99133694  1.2573972 ]
 [-2.0104504  -1.7413595  -0.28711194  0.18983224  1.8718754 ]
 [-1.4673029  -1.2721989  -0.7803738  -0.06164822  0.94073033]
 [-2.0842526  -1.451092   -0.96740866 -0.88693523  0.61423135]
 [-2.0105364  -0.6974499  -0.52970064  0.5391437   0.94831836]], shape=(5, 5), dtype=float32)


## Menampilkan Nilai concatenation

In [39]:
print("size original data : ",prime_tensor.shape,random_tensor.shape)
list_prima_tensor = tf.concat([prime_tensor,random_tensor],axis=0)
print("size concat data : ",prime_tensor.shape)

size original data :  (5, 5) (5, 5)
size concat data :  (5, 5)


## Menampilkan hasil dari kedua variable di atas(Descending)

In [40]:
tf.sort(random_tensor, direction="DESCENDING")
tf.sort(prime_tensor, direction="DESCENDING")

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)>